apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: content-platform
type: Opaque
stringData:
  # Remplacer par la vraie connection string lors du d√©ploiement
  # kubectl apply -f k8s/secret.yaml
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=placeholder;AccountKey=placeholder;EndpointSuffix=core.windows.net"
