apiVersion: v1
kind: Service
metadata:
  name: content-platform-svc
  namespace: content-platform
spec:
  selector:
    app: content-platform
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
